[project]
name = "assignment-3-142402006"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pillow>=11.3.0",
    "toml>=0.10.2",
    "torch>=2.8.0",
    "torchvision>=0.23.0",
]
